class Semester{
  String id='';
  String period='';
}
//RECOMENDACION PARA CARLOS DEL FUTURO: LAS FOREIGN KEY HACELAS DEL TIPO DE LA
// LLAVE QUE VAYAS A OCUPAR POR EJEMPLO USER_ID PONDRIAMOS UN CAMPO USER USER_ID
// O SINO UN CAMPO ENROLLED_ID PONDRIAMOS UN CAMPO ENROLLED ENROLLED_ID
// TAMBIEN RESPETA EN LO POSIBLE LOS TIPOS DE DATOS, NO HAGAS STRING TTODO A LO LOCO